name: Google Cloud CLI Action

on:
  push:
    branches:
      - main

jobs:
  gcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        run: |
          echo "Installing Google Cloud SDK..."
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      - name: Authenticate to Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo ${{ secrets.GCLOUD_SERVICE_KEY }} > ${HOME}/gcloud-key.json
          jq -c . ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json

      - name: Run gcloud commands
        run: |
          gcloud config set project ${{ secrets.GCLOUD_PROJECT_ID }}
          gcloud builds submit --tag

      - name: Send Slack Notification on Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"❌ Pipeline failed in repository '"$GITHUB_REPOSITORY"' on branch '"$GITHUB_REF"'. Check it out: '"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"'"}' $SLACK_WEBHOOK_URL
