on: [push, pull_request]

jobs:
  gcloud-login:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}  # Your Google Cloud project ID
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true

      # Optional: Authenticate Docker to use Google Container Registry if needed
      - name: Build and Push Docker Image
        run: |
          gcloud config set account ${{ secrets.GCLOUD_ACCOUNT_EMAIL }} 
          gcloud builds submit --tag gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/my-node-app

      # Example: Run gcloud commands here (e.g., deploy to App Engine, Kubernetes, etc.)
